# The Jenkins server.
jenkins:
  image: 'jenkins:latest'
  ports:
    - 8080:8080
  volumes_from:
  - data
  privileged: true
data:
  image: busybox
  volumes:
    - ./jenkins_home:/var/jenkins_home:rw
  command: ["chown", "-v", "-R", "1000:1000", "/var/jenkins_home"]


